connectionString: jdbc:postgresql://localhost:5432/testdb?user=postgres&password=postgres
statusTable: tx_status
adjustWorkers: 1 # 0 to disable
adjustDelta: 1000 #ms
adjustWindow: 25 # percentage of adjustDelta
minAverageAmountPerNode: 1
maxNodes: 1024
minNodes: 1
arGoal: 0.05
arMin: 0.01
balanceWorkers: 0 # 0 to disable
balanceDelta: 100 #ms
balanceWindow: 100 # percentage of balanceDelta
balanceMinDiff: 10 # percentage between min and max
balanceMinmaxK: 1
balanceMinmaxKRatio: 16
balanceAlgorithm: minmax # random | minmax
monitor: true
monitorDelta: 2000 #ms
monitorTables:
  - warehouse1_w_ytd
  - district1_d_ytd
